### ISSUE TITLE
Error when debug your repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [obayomi96/blinkalert#2]
Hello:
I added one more option to your repo., so the extension will show alert every 2 minutes.
I loaded your extension using load unpacked on my current Chrome (Version 88.0.4324.190 (Official Build) (64-bit)).
However, when I tried to debug background script, I found the following error:
Uncaught TypeError: Cannot read property 'value' of null
    at background.js:10
This line is:
var optionVal = document.getElementById('duration').value;
I added this line to popup.html:
        <option value="120000">2 Min</option>
Let me know if I made any mistake.
Thanks,

**Comment by obayomi96** [comment]
Thanks for your feedback @zydjohnHotmail , a new version is currently in review and will be published soon, and this issue would have been fixed, I will notify here and close this issue once the new version is released soon!. Thanks again!
